services:

  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: iqlab@2025
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: iqlab@2025
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    depends_on:
      - mysql-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: iqlab@2025
      ZBX_STARTAGENTS: 5
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    restart: unless-stopped

  zabbix-web:
    image: ghcr.io/iqlab2025/my-zabbix:custom
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - mysql-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: iqlab@2025
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/London
    ports:
      - "8080:8080"
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    container_name: zabbix-agent
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      HOSTNAME: zabbix-agent
    ports:
      - "10050:10050"
    restart: unless-stopped

volumes:
  mysql-data:
  zabbix-server-data:
  zabbix-web-data:
